version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpw
      POSTGRES_DB: subway-postgres
    ports:
      - "5432:5432"